### ISSUE TITLE
clipr package dependency missing in README

### ISSUE THREAD

**Issue by RLesur** [sbihorel/rclipboard#2]
Hi Sébastien, (j'écris en anglais même si j'ai vu que tu étais français)

I recently discovered clipboard.js and I thank you for your work.
I installed rclipboard from CRAN and I ran the minimal example and got an error since clipr package was not installed.
I think README could be updated with `library(clipr)`.

Romain

**Comment by sbihorel** [comment]
Hi,

Package dependencies must be handled in the DESCRIPTION file. Because rclipboard does not rely on the clipr library per se, I did not include it  as a hard dependency. I do not believe that README files are checked during R CMD check or CRAN package checks, so adding library(clipr) to the README file should not change anything to the problem you raised.
I will see what are the consequences of adding clipr as a suggested package in the DESCRIPTION file.

Thanks for your post

**Comment by sbihorel** [comment]
Closing
